version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql-sakila
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sakila
    volumes:
      - mysql_sakila_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:1234"

  app:
    build: .
    container_name: next-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "un_secreto_muy_largo"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_sakila_data:
